# fly.toml app configuration file generated for nanomq-testing on 2023-10-06T20:08:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
###

app = "nanomq-testing"
primary_region = "ams"

[build]
  image = "emqx/nanomq:0.19.5"

[[services]]
  protocol = "tcp"
  internal_port = 1883

  [[services.ports]]
    port = 1883

  [[services.ports]]
    port = 8083
    handlers = ["http"]

  [[services.ports]]
    port = 8883
    handlers = ["tls"]
