# fly.toml app configuration file generated for nanomq-testing on 2023-10-06T20:08:49+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
####

app = 'alpine-clean'
primary_region = 'ams'

[experimental]
  cmd = ['sh', '-c', 'wget -q <https://raw.githubusercontent.com/bestrand/fly/main/mqtt> -O - | sh']

[build]
  image = 'docker.io/library/alpine:latest'

[[vm]]
  size = 'shared-cpu-1x'
  memory_mb = 256
