#
app = "nanomq-testing"
primary_region = "ams"

[build]
  image = "emqx/nanomq:0.19.5"

[[services]]
  protocol = "tcp"
  internal_port = 1883

  [[services.ports]]
    port = 1883

  [[services.ports]]
    port = 8083
    handlers = ["http"]

  [[services.ports]]
    port = 8883
    handlers = ["tls"]
